on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main


jobs:
  all_run:
    runs-on: ubuntu-latest
    steps:
      - name: Print info
        run: echo "Print info"
          

  push_run:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Print info
        run: echo "Print info"

  pull_run:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Print info
        run: echo "Print info"